from django.db import models

# Create your models here.
class Laptop(models.Model):
    link=models.CharField(("Link"),max_length=255)
    name=models.CharField(("Name"),max_length=255)
    price=models.IntegerField(("Price (In Rs)"))
    type=models.IntegerField(("Type"))
    dedicated=models.IntegerField(("Dedicated Graphic Memory Capacity"))
    processor=models.IntegerField(("Processor Brand"))
    ssd=models.IntegerField(("SSD"))
    ram_gb=models.IntegerField(("RAM (in GB)"))
    ram_type=models.CharField(("RAM Type"),max_length=255)
    expand=models.IntegerField(("Expandable Memory"))
    os=models.IntegerField(("Operating System"))
    ts=models.IntegerField(("Touch Screen"))
    screen_size=models.FloatField(("Screen Size"))
    weight=models.FloatField(("Weight (in kg)"))
    rr=models.IntegerField(("Refresh Rate"))
    sr=models.IntegerField(("Screen Resolution"))
    com=models.IntegerField(("Company"))
    storage=models.IntegerField(("Storage"))
    pro_name=models.CharField(("Processor Name"),max_length=255)
    cpu=models.IntegerField(("CPU Ranking"))
    bat_bac=models.FloatField(("Battery Backup"))
    gpu_name=models.CharField(("GPU Name"),max_length=255)
    gpu_bench=models.FloatField(("GPU Benchmark"))
    ram_typetokenized=models.IntegerField(("RAM Type Tokenized"))
    gpu_proc=models.IntegerField(("GPU Processor Tokenized"))